# Generated by Django 3.2.6 on 2022-11-04 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_authourprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthourProfile',
            new_name='AuthorProfile',
        ),
    ]
